### ISSUE TITLE
RedDroneWormAgent incorrect behaviour

### ISSUE THREAD

**Issue by comet834** [cage-challenge/CybORG#11]
In the `RedDroneWormAgent`'s `get_action` function, behaviour 3 is supposed to exploit neighbouring drones, but attempts to flood drones that are as far away as possible (as in behaviour 1).

**Comment by maxstanden** [comment]
I see the issue that it is targeting drones that are far away but it looks like it is still using ExploitDroneVulnerability rather than FloodBandwidth in behaviour 3. Was that the issue you meant? Otherwise if you have found a bug where FloodBandwidth is still being taken in behaviour 3, would you mind sharing the code you used to identify that issue so that we may replicate it?

**Comment by comet834** [comment]
Apologies, my initial comment was misleading - it was just the issue with targeting drones that are far away that I spotted. As far as I'm aware, there are no issues with FloodBandwidth vs ExploitDroneVulnerability. Thanks!

**Comment by maxstanden** [comment]
We have corrected the description of behaviour 3, as this is still a valid behaviour for the Red Agent.
